Use official 3ds target
zaksabeast/libctr-rs pull request #1
Opened 2022-07-22 22:47 UTC by SteveCookTU

2022-07-23 02:17 UTC, zaksabeast requested changes
Thank you!

In additional to the comments, we should also remove hashbrown and cstr_core.  Those come with the standard library, and hashbrown seems to have a libc conflict with ctru-rs.

Before merging, I'd also like to make sure this works with PokeReader and the friend sysmodule rewrite.

2022-07-23 02:17 UTC, zaksabeast commented on Cargo.toml
> +ctru-sys = { git = "https://github.com/Meziu/ctru-rs.git" }
Let's bound this to a specific commit to prevent breaking changes from causing issues and having different builds depending on when dependencies are pulled (e.g. two CI runs can produce different binaries without changing anything).

2022-07-23 02:17 UTC, zaksabeast commented on src/svc/ctr.rs
> +use std::mem::transmute;
Let's use this import for consistency:
```suggestion
use std::{arch::asm, convert::TryInto, ffi::c_void, mem::transmute};
```

2022-07-23 02:17 UTC, zaksabeast commented on Makefile
> +CARGO_BUILD_FLAGS = -Z build-std=core,alloc --target armv6k-nintendo-3ds
The makefile doesn't work if it builds core, but the files use std:
```suggestion
CARGO_BUILD_FLAGS = -Z build-std --target armv6k-nintendo-3ds
```

2022-07-24 00:15 UTC, SteveCookTU commented on src/svc/ctr.rs
> +use std::mem::transmute;
Thoughts on adding the nightly formatting that was added for nex-rs?

2022-07-24 00:15 UTC, SteveCookTU commented on Makefile
> +CARGO_BUILD_FLAGS = -Z build-std=core,alloc --target armv6k-nintendo-3ds
Thought I removed this, good catch!

2022-07-24 00:19 UTC, SteveCookTU commented on Cargo.toml
> +ctru-sys = { git = "https://github.com/Meziu/ctru-rs.git" }
I am able to specify a version but not a commit. The issue is after adding the pthread and linker fix that the two repos don't specify a commit or version so the latest is used.

2023-01-14 18:40 UTC, closed without merging